# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron text

on:
  push:
    tags: 
      - 'v*.*.*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
   name: build and release electron
   runs-on: ${{ matrix.os }}
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        os: [windows-2019]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install
  
      - run: npm start
      - run: npm run build --if-present
      - run: npm test
